# Generated by Django 5.0.3 on 2024-04-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0002_alter_tarea_idtarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fechaComienzo',
            field=models.DateField(auto_now_add=True),
        ),
    ]
