# Generated by Django 5.0.3 on 2024-04-03 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipoUsuario',
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idTarea', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreTarea', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('fechaComienzo', models.DateField()),
                ('fechaVencimiento', models.DateTimeField()),
                ('usuarioAsignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='tipoUsuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
