# Generated by Django 5.0.3 on 2024-04-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_remove_usuario_tipousuario_tarea_delete_tipousuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
